### ISSUE TITLE
WiFi Disconnect and Failed Reconnect

### ISSUE THREAD

**Issue by lbussy** [lbussy/keg-cop#164]
On occasion, the WiFi connection will disconnect and fail to reconnect:

```
[WiFi-event] event: 5
2023-04-12T14:17:46Z W: WiFi lost connection, reconnecting ..
[WiFi-event] event: 5
[WiFi-event] event: 4
[WiFi-event] event: 7
[WiFi-event] event: 1
[WiFi-event] event: 5
[WiFi-event] event: 4
[WiFi-event] event: 7
[WiFi-event] event: 1
[WiFi-event] event: 5
[WiFi-event] event: 4
[WiFi-event] event: 7
2023-04-12T14:18:03Z N: Reboot request - rebooting system.
[WiFi-event] event: 5
[WiFi-event] event: 3
```

This seems to be the same as [Wifi connection fails - only works after router reboot #8412](https://github.com/esp8266/Arduino/issues/8412) in the ESP8266 core for Arduino, and is explained REALLY well in [ESP32 STA deauth frame causing reconnect issues (IDFGH-6544) #8192](https://github.com/espressif/esp-idf/issues/8192).  The tracing tablatronix did here almost mirrors what I saw.

So now, I get to find a more graceful way (e.g. a hack) to recover from this because even if the newer core is better, it exhibits quite a bit more instability.

Thankfully, this results in a controlled restart (under Keg cop control) so it's not horrible.  The worst part of it is that the compressor lockout may cause a kegerator to be off while that timeout runs out.

**Comment by thorrak** [comment]
Did you actually fire up wireshark and see the same deauth frame coming through? I ask, as that's something I was experiencing personally earlier, but have not been experiencing since more recent versions of esp-idf (via more recent Arduino framework releases) have been available

**Comment by lbussy** [comment]
"Good enough" for now.  There is a compile-time define for `TRY_WIFI_RECONNECT` in `wifihandler.cpp` if I want to try again.  Right now it reboots on WiFi failure.
