### ISSUE TITLE
Clicking Renumbered Taps From Main Screen Takes You To Wrong Tap Settings

### ISSUE THREAD

**Issue by MichaelPersico** [lbussy/keg-cop#211]
When clicking a tap on the main screen it seems to only follow a numerical order no matter what taps are inactive or renumbered.  I currently have taps 1, 2, 4, and 5 active.  I have also renumbered taps 4 and 5 to show up as 3 and 4 on the home screen.  When clicking the renumbered tap 3, which is actually tap 4, it takes me to tap 3 settings even though tap 3 is inactive.

**Comment by lbussy** [comment]
Unfortunately, this is a data versus display thing.  Each tap has a discrete pin, so they stay that way internally.  I allowed a "label" to renumber it, but you will always be skipping slots.  If @thorrak ever writes the elusive KegScreen, it will remove this hardware correlation.

**Comment by lbussy** [comment]
Closing this one as "working as designed."  If a new idea pops up to address this hardware vs. UI issue, I'm all ears.
