### ISSUE TITLE
Controller Crash

### ISSUE THREAD

**Issue by lbussy** [lbussy/keg-cop#26]
From #20

> I'm not sure what happened, but as of these last few builds I can no longer monitor serial out.
> As soon as I connect via PuTTY it causes a panic (see log below).
> Also, rebooting doesn't fix it. I have to hold the 'boot' button for a few seconds before it will properly reload the firmware.
> 
> If I don't connect on the serial line and just let it go then it works fine and I can interact with it via the webpage / API.

```
    rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
    configsip: 0, SPIWP:0xee
    clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
    mode:DIO, clock div:2
    load:0x3fff0018,len:4
    load:0x3fff001c,len:1044
    load:0x40078000,len:10044
    load:0x40080400,len:5872
    entry 0x400806ac

    1970-01-01T00:00:00Z N: Serial logging started at 115200.
    1970-01-01T00:00:00Z V: Starting WiFi.
    *WM: [1] Free heap: 246792
    *WM: [1] ESP SDK version: v3.3.5-1-g85c43024c
    *WM: [3] allocating params bytes: 20
    *WM: [2] Added Parameter: name
    *WM: [1] AutoConnect.
    *WM: [2] esp_wifi_set_country: US
    *WM: [2] ESP32 event handler enabled.
    *WM: [2] Connecting as WiFi client.
    *WM: [3] STA static IP:
    *WM: [2] setSTAConfig static ip not set, skipping.
    *WM: [1] Connecting to saved AP: REDACTED
    *WM: [3] Using password: REDACTED
    *WM: [3] WiFi_enableSTA: enabled.
    *WM: [3] Mode after delay: STA
    *WM: [2] 30000 ms connectTimeout set.
    *WM: ▒▒] 30000 ms timeout, waiting for connection................Guru Meditation Error: Core panic'ed (Interrupt wdt timeout on CPU0)
    Core 0 register dump:
    PC 0x40086e6 PS 0x00060834 A0 0x8012c10 A1 0x3fa3e
    A2 0x3fc604 A3 0x00000000 A4 0x00000000 A5 0x3fcd0
    A6 0x00000002 A7 0x00000100 A8 0x8008a44 A9 0x3fa3f
    A10 0x00000005 A11 0x00060c3 A12 0x00060c0 A13 0x3fa488
    A14 0x00000017 A15 0x00000000 SAR 0x00000020 EXCCAUSE 0x00000005
    EXCVADDR 0x00000000 LBEG 0x4000ce LEND 0x4000cf LCOUNT 0xffff

    ELF file SHA256: 000000000000000

    Backtrace:0x40086e6:0x3fa3e 0x4012c0d0x3fa420 0x4012c19:0x3fa450 0x40130ff0x3fa480 0x40089be0x3fa4b

    ore 1 register dump:
    PC 0x4018762a PS 0x00060834 A0 0x8016d1e A1 0x3fb7a
    A2 0x00000000 A3 0x00000001 A4 0x80089d0 A5 0x3fba0
    A6 0x00000000 A7 0x3fb4a A8 0x00060023 A9 0x3fb310
    A10 0x00000000 A11 0x00000001 A12 0x80089d0 A13 0x3fb8b
    A14 0x00000000 A15 0x3fb4a SAR 0x00000000 EXCCAUSE 0x00000005
    EXCVADDR 0x00000000 LBEG 0x00000000 LEND 0x00000000 LCOUNT 0x00000000

    ELF file SHA256: 000000000000000

    Backtrace:0x4018762a0x3fb7a 0x4016d1b0x3fb7c 0x4008b7d0x3fb7e 0x40089be0x3fb800

    Rebooting...
```

**Comment by austinpe** [comment]
Hmm. The panic isn't just on Serial connection either.

![image](https://user-images.githubusercontent.com/587046/175830975-8fb01351-afe5-487b-89a9-d7f6bd7876fa.png)

I just checked the web interface and it seems the temp is slowly going up and up because the esp32 keeps rebooting due to a panic.
Then the thermostat never triggers because it's in "minimum off time" (which is fine). But, basically it seems that the device is not staying on for longer than 5 min at a time

**Comment by lbussy** [comment]
Well that's strange. I looked at mine and it's definitely reset.  It sounds like mine is running longer:

![image](https://user-images.githubusercontent.com/9092188/175831233-0171e898-50b9-49f7-8d7c-909faebfc834.jpeg)

Yay, library issues!

**Comment by austinpe** [comment]
Here's another log dump on a freshly flashed esp32 and after setting up the wifi.
You can see that it connects, starts up, and then fails.

> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0018,len:4
> load:0x3fff001c,len:1044
> load:0x40078000,len:10044
> load:0x40080400,len:5872
> entry 0x400806ac
> 
> 1970-01-01T00:00:00Z N: Serial logging started at 115200.
> 1970-01-01T00:00:00Z V: Starting WiFi.
> *WM: [1] Free heap:        246792
> *WM: [1] ESP SDK version:  v3.3.5-1-g85c43024c
> *WM: [3] allocating params bytes: 20
> *WM: [2] Added Parameter: name
> *WM: [1] AutoConnect.
> *WM: [2] esp_wifi_set_country: US
> *WM: [2] ESP32 event handler enabled.
> *WM: [2] Connecting as WiFi client.
> *WM: [3] STA static IP:
> *WM: [2] setSTAConfig static ip not set, skipping.
> *WM: [1] Connecting to saved AP: REDACTED
> *WM: [3] Using password: REDACTED
> *WM: [3] WiFi_enableSTA:  enabled.
> *WM: [3] Mode after delay: STA
> *WM: [2] 30000 ms conne▒Q▒▒▒▒▒сset.
> *WM: [2] 30000 ms timeout,@waiting for connection....................................
> *WM: [2] Connection result: WL_CONNECTED
> *WM: [3] lastconxresult: WL_CONNECTED
> *WM: [1] AutoConnect: SUCCESS
> *WM: [1] STA IP address: 192.168.0.60
> 1970-01-01T00:00:04Z N: Connected. IP address: 192.168.0.60.
> *WM: [3] Freeing allocated parameters.
> *WM: [3] Unloading AsyncWiFiManager.
> 1970-01-01T00:00:04Z N: Entering blocking loop to get NTP time..
> 2022-06-26T19:45:58Z N: NTP time set.
> 2022-06-26T19:45:58Z N: Flowmeters loaded.
> 2022-06-f6T19:45:58Z V: No OTA pending.
> 2022-06-26T19:45:58Z N: mDNS responder started for devkegcop.local.
> 2022-06-26T19:45:58Z N: HTTP registered via mDNS on port 80.
> 2022-06-26T19:45:58Z N: Async HTTP server started on port 80.
> 2022-06-26T19:45:58Z V: Open: http://devkegcop.local to view application.
> 2022-06-26T19:45:58Z V: MQTT: Creating process.
> 2022-06-26T19:45:58Z N: Started Keg Cop version 1.0.1-Alpha.3/1.0.1-Alpha.3 (fix_kk_report) [6971746].
> 2022-06-26T19:46:03Z V: MQTT: No broker configured.
> 2022-06-26T19:46:08Z V: MQTT: No broker configured.
> 2022-06-26T19:46:08Z V: Keg Screen reporting not enabled, skipping.
> ur MdiatonEror Cre anc'd Inerup wt imou o CU1)
> C     000c71 S     000004  A0    : x80878 1     0fb1d40
> 2     0fb0058 3      0x3f41c8c  4      0x00000014 5      0x3ff0000
> A6      0x3ff0048 7      0x00000001 8     : x0000001 9     : xf184d
> A0     0x000000a5 11     0x3ff0060 12     0x8008b38f A3     0x3fbfd
> 14    : 0000008 15    : x0000001 AR    : x000001f ECCUSE 0x00000006
> ECVADR: x0000000  LBEG    0x400014fd LEND    0x4000150d LOUT   0xfffff
> 
> ELF fle SA256: 000000000000
> 
> Bactrac: 0x40c7:0x3ff1d40 040a7d50xffbd60 x408c3800xffbd80 x408c3360xffce30
> 
> Coe 0 rgisterdump
> P     : x0086e26 S      0x00060d34 0     : x80148ea  A1      0x3ff5480
> A2    : 0x3fc61 A      0x3ff54ac A4      0x0000000d A      0x000000ac
> A6      0x00000000 7      0x00060423  A8      0x8014e585 9      0x3ff5450
> A1      0xfffff A1     0x3ff54ac  12     0x0000000d A3     0x00003f68
> A1    : 0x00000011 15     0x00000011 AR    : x0000019  EXCCUSE 0x00000006
> EXCVDDR 0x00000000 BEG   : x4000c2e0 EN     0x4000c2f6 CONT   0xfffff
> 
> ELFfile SA256 0000000000000
> 
> Bactrac: 0x4086e260xffb40 0x048ea:03fb400x089bc:03fb40
> 
> ebooing..
>

**Comment by lbussy** [comment]
When I get done cooking I'll re-compile 1.0.0 and see if the problem persists.  If it does, it will be an upstream change.

**Comment by lbussy** [comment]
Okay, I ran all night on 1.0.0.  Back on the Alpha code now.

**Comment by austinpe** [comment]
I'll try out this version after work!

I noticed that it does go for longer than 5 min; it has gotten up to an hour or so. But, I can't seem to zero in on what causes it.

It was risky, but I let it run over night. The temp was within 1° of target, so it _is_ able to cool, but it's restarting constantly.

Here's the a screenshot as I'm writing this message to show that it can go over 5min but is still happening.

![image](https://user-images.githubusercontent.com/587046/176010657-c81e6a61-7303-4c08-8460-541cbe40a6c7.png)

**Comment by austinpe** [comment]
It seems the firmware is not longer in your github?
The address that BrewFlasher looks for is 404.

I looked in the 'debug reset' branch and it seems that the compiled firmware in there is a few days old, so I'm not sure if they are correct, but I'll try them.

**Comment by lbussy** [comment]
Thaaaaats weird.

Gimme a sec. :)

**Comment by thorrak** [comment]
> Thaaaaats weird.
> 
> Gimme a sec. :)

Wasn't me. (this time)

**Comment by lbussy** [comment]
No, it was me.  _Apparently_ when I delete a tag, the release it was tied to breaks.  Go figure.

**Comment by austinpe** [comment]
I had a really hard time finding the recommended D32 for this project (Lolin D32 v1.0.0).
I found other ones for cheaper on amazon and just had to do a breadboard to the PCB header.

Did you re-release the debug build on github?

**Comment by lbussy** [comment]
I did:

[1.0.1-Debug.1](https://github.com/lbussy/keg-cop/releases/tag/1.0.1-Debug.1)

John broke BrewFlasher again so you will have to do it manually.  Pay attention to the partition table changes, they are [listed here](https://github.com/lbussy/keg-cop/blob/reboot_timers/4mb_inc_ota.csv).

**Comment by lbussy** [comment]
Key (helpful) change:  The system will log uptime and reboot reasons in `uptime.csv`.  Go to the `/edit` page (un: admin, pw: p@ssword) and right click the file to download the csv:

<img width="144" alt="image" src="https://user-images.githubusercontent.com/9092188/176274415-194272db-4e3a-45dd-ac91-5d4dd33f9f89.png">

**Comment by lbussy** [comment]
John fixed BrewFlasher:

https://web.brewflasher.com/fw/78/

**Comment by austinpe** [comment]
awesome. I was having trouble with the new offsets. I'll try brewflasher now

**Comment by austinpe** [comment]
I got it connected to the network. 
Web interface loaded fine.

Tried to connect via Serial and had the following.
It seems that on connect it reboots the device, then panics, then reboots, panics, and then hangs.
I'll keep digging.
> ets Jun  8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0030,len:1184
> load:0x40078000,len:12784
> load:0x40080400,len:3032
> entry 0x400805e4
> 
> 1970-01-01T00:00:00Z N: Serial logging started at 115200.
> 1970-01-01T00:00:00Z V: Starting WiFi.
> *WM: [1] Free heap:        246888
> *WM: [1] ESP SDK version:  v3.3.5-1-g85c43024c
> *WM: [3] allocating params bytes: 20
> *WM: [2] Added Parameter: name
> *WM: [1] AutoConnect.
> *WM: [2] esp_wifi_set_country: US
> *WM: [2] ESP32 event handler enabled.
> *WM: [2] Connecting as WiFi client.
> *WM: [3] STA static IP:
> *WM: [2] setSTAConfig static ip not set, skipping.
> *WM: [1] Connecting to saved AP: REDACTED
> *WM: [3] Using password: REDACTED
> *WM: [3] WiFi_enableSTA:  enabled.
> *WM: [3] Mode after delay: STA
> *WM: ▒2] 30000 ms connectTimeout set.
> *WM: [2] 30000 ms timeout, waiting for connection....GGuru Meditation Error: Cor                                                                                    e  1 panic'ed (Unhandled debug exception)
> Debug exception reason: BREAK instr
> Core 1 register dump:
> PC      : 0x400803c0  PS      : 0x00060036  A0      : 0x4008c383  A1      : 0x3f                                                                                    fbd6c0
> A2      : 0x00050023  A3      : 0x00000000  A4      : 0x00000001  A5      : 0x00                                                                                    000001
> A6      : 0x00000001  A7      : 0x00060c23  A8      : 0x0000000c  A9      : 0x00                                                                                    000000
> A10     : 0x00000000  A11     : 0x00000000  A12     : 0x3ffc8e5c  A13     : 0x3f                                                                                    fb796c
> A14     : 0x00000001  A15     : 0x00000001  SAR     : 0x00000016  EXCCAUSE: 0x00                                                                                    000001
> EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00                                                                                    000000
> 
> ELF file SHA256: 0000000000000000
> 
> Backtrace: 0x400803c0:0x3ffbd6c0 0x4008c380:0x3ffbd6e0 0x4008c336:0xa5a5a5a5
> 
> Rebooting...
> ets Jun  8 2016 00:22:57
> 
> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0030,len:1184
> load:0x40078000,len:12784
> load:0x40080400,len:3032
> entry 0x400805e4
> 
> 1970-01-01T00:00:02Z N: Serial logging started at 115200.
> 1970-01-01T00:00:02Z V: Starting WiFi.
> *WM: [1] Free heap:        246888
> *WM: [1] ESP SDK version:  v3.3.5-1-g85c43024c
> *WM: [3] allocating params bytes: 20
> *WM: [2] Added Parameter: name
> *WM: [1] AutoConnect.
> *WM: [2] esp_wifi_set_country: US
> *WM: [2] ESP32 event handler enabled.
> *WM: [2] Connecting as WiFi client.
> *WM: [3] STA static IP:
> *WM: [2] setSTAConfig static ip not set, skipping.
> *WM: [1] Connecting to saved AP: REDACTED
> *WM: [3] Using password: REDACTED
> *WM: [3] WiFi_enableSTA:  enabled.
> *WM: [3] Mode after delay: STA
> *WM: ▒▒] 30000 ms connectTimeout set.
> *WM: [2]▒30000 ms timeout, waiting for connection.....Guru Meditation Error: Cor                                                                                    e  panic'ed (Double exception)
> Core 0 register dump:
> PC       0x40089cf PS       0x00060036  A0       0x80085a6  A1       0x3fb9b
> A2       0x00000000  A3       0x3fb96c A4       0x92901199  A5       0x00000001                                                                                     
> A6       0x00060021  A7       0x00000400  A8       0x00000001  A9       0x000000                                                                                    01
> A10      0x00060023  A11      0x00060023  A12      0x00060021  A13      0x3fb96c                                                                                    
> A14      0x00000006  A15      0x00000000  SAR      0x00000000  EXCCAUSE 0x000000                                                                                    02
> EXCVADDR 0x00000002  LBEG     0x4000ce  LEND     0x4000cf  LCOUNT   0xffff
> Core was running in ISR context:
> EPC1    : 0x40089cf  EPC2    : 0x00000000 EPC3    : 0x00000000 EPC4    : 0x00000                                                                                    000
> 
> ELF file SHA256: 000000000000000
> 
> Backtrace:0x40089cf0x3fb9b 0x40085a3:0x3fb9d 0x400841b:0x3fb9f 0x40081bd0x3fba00                                                                                    x4008707d0x3fba00x4013814d0x3fb810 0x4012f83:0x3fb830 0x401434f:0x3fb850 0x40143                                                                                    521:0x3fb870 0x4019cb:0x3fb890 0x4019c2b0x3fb8b 0x40089be0x3fb8d
> 
> Rebooting...
>

**Comment by lbussy** [comment]
> Core was running in ISR context:

Disconnect any of your flowmeters and see what happens.

**Comment by austinpe** [comment]
That was a new esp32 with nothing connected.

But, I started to think when you said you had to find a new esp32.
I just flashed another brand ESP32 (this one only has 30 pins instead of 38) and it has been up for 20min with both web interface and serial connected...

So, I wonder if the issue was with an incompatibility with this specific board+ libraries? 
It's weird that both boards of the same brand had the panic and now this new one doesn't.

I'll keep monitoring

**Comment by lbussy** [comment]
That could be - it makes sense.  WiFi and BLE use some pins on some boards and not others.  This was written on Lolin D32 (regular, not pro) so that may guide you a bit.

For what its worth, I did not change anything having to do with pins.

**Comment by lbussy** [comment]
Here's the pinout:  https://www.wemos.cc/en/latest/d32/d32_pro.html

**Comment by austinpe** [comment]
I just reflashed v1 on the board that was panicing.
No issues so far -- I can connect to both web and serial at the same time.
It's been up for 10min now.

So, it has to be some combo of new libraries (?) and the board.

Here's the pinout of the board that panics on the new version:
![image](https://user-images.githubusercontent.com/587046/176324180-a7545230-d1bf-426d-a3ee-8ea0561157c6.png)


And here's the pinout of the board that seems to be doing ok (so far) with the new version:
![image](https://user-images.githubusercontent.com/587046/176324243-41cf767d-454f-48ca-b170-361e5d1e3ef7.png)

**Comment by austinpe** [comment]
Hmm. I spoke too soon about this new board.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Austin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Austin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Date/Time | Start Reason | Restart Description | Uptime   (Secs)
-- | -- | -- | --
2022-06-29T01:07:12Z | ESP_RST_POWERON | START_COLDBOOT | 311
2022-06-29T01:51:19Z | ESP_RST_SW | START_COLDBOOT | 2586
2022-06-29T02:06:36Z | ESP_RST_PANIC | START_WARMBOOT | 905
2022-06-29T02:33:58Z | ESP_RST_PANIC | START_WARMBOOT | 1626
2022-06-29T02:58:11Z | ESP_RST_PANIC | START_WARMBOOT | 1446



</body>

</html>

**Comment by lbussy** [comment]
Here's where we need to get you running with PlatformIO and you can try a few things.  Are you able to clone the repo and get this branch to compile?  If so I can suggest a few things to rule in/out some of the pin sets to narrow it down.

**Comment by lbussy** [comment]
Also:  I have deleted the debug download and replaced it with `1.1.0-Alpha.1` to reflect the semantic versioning of what will be a release.

[Keg Cop 1.1.0-Alpha.1](https://web.brewflasher.com/fw/81/)

**Comment by austinpe** [comment]
I'll try to download and compile on my own now. 
I'll let you know how it goes!

I'm currently at 10 hours of uptime which I think is the longest stretch. 
I was curious if the panics were related to interactivity or if they were random.
My keezer obviously doesn't get a ton of use during morning/day time, but I do have nitro coffee on tap that's being tracked, so it did get some use early this morning and didn't crash.

Also, I have it sending data to a server via the Keg Screen feature.

I just wanted to write out my full use case in case it has any helpful hints.

**Comment by thorrak** [comment]
When was the last time you updated the espressif32 package in platformio?

**Comment by lbussy** [comment]
> When was the last time you updated the espressif32 package in platformio?

I just installed PIO on here so not too long ago.

**Comment by lbussy** [comment]
Yeah ... I've got work to do because of the new platform packages.

**Comment by lbussy** [comment]
Updated [Keg Cop Alpha](https://web.brewflasher.com/fw/81/) to 1.1.0-Alpha.2

You'll have to `git fetch --all` and `git checkout taplist_io` to get this branch.  It _might_ fix the crashes - check it.

**Comment by austinpe** [comment]
It got SO much further this time, but still had an issue in the Onewire library file OneWire_direct_gpio.h

> In file included from .pio/libdeps/lolin_d32/OneWire/OneWire.cpp:144:
> .pio/libdeps/lolin_d32/OneWire/util/OneWire_direct_gpio.h: In function 'void directModeInput(uint32_t)':
> .pio/libdeps/lolin_d32/OneWire/util/OneWire_direct_gpio.h:161:26: error: 'rtc_gpio_desc' was not declared in this scope
>          uint32_t rtc_reg(rtc_gpio_desc[pin].reg);

**Comment by lbussy** [comment]
Click on the alien, drop down lolin_d32 under Project Tasks, General. "Clean all":

<img width="381" alt="image" src="https://user-images.githubusercontent.com/9092188/176554585-79a99464-5966-46cd-8261-6d69049b7f79.png">

**Comment by lbussy** [comment]
You should try the one I added to BrewFlasher as well.

**Comment by austinpe** [comment]
I'm trying the new one from BrewFlasher.

I tried the 'clean all' task and it for some reason ended up with a 'permission denied' error. I tried to troubleshoot this and everything seemed to just blame antivirus. I tried disabling everything, but still got the same error. 
I tried running in admin mode.
I forked the repo and tried that in admin mode -- always the same error.

But, it seemed to help regardless as it allowed the 'build' task to get further. Now, it's an issue with 

> Compiling .pio\build\lolin_d32\lib4d9\LittleFS_esp32\lfs.c.o
> .pio/libdeps/lolin_d32/LittleFS_esp32/src/esp_littlefs.c:19:2: warning: #warning ("Use the built-in LITTLEFS library") [-Wcpp]
>  #warning("Use the built-in LITTLEFS library")
>   ^~~~~~~
> .pio/libdeps/lolin_d32/LittleFS_esp32/src/LittleFS.cpp: In member function 'virtual bool LITTLEFSImpl::exists(const char*)':
> .pio/libdeps/lolin_d32/LittleFS_esp32/src/LittleFS.cpp:44:28: error: no matching function for call to 'LITTLEFSImpl::open(const char*&, const char [2])'
>      File f = open(path, "r");
>  ______________________^
> In file included from .pio/libdeps/lolin_d32/LittleFS_esp32/src/LittleFS.cpp:17:
> C:/Users/Austin/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.h:38:17: note: candidate: 'virtual fs::FileImplPtr VFSImpl::open(const char*, const char*, bool)'
>      FileImplPtr open(const char* path, const char* mode, const bool create) override;
> ____________^~~~
> Archiving .pio\build\lolin_d32\lib88e\libESPTelnet.a

**Comment by austinpe** [comment]
I know you're not here to provide platformIO support. I'll try to figure it out myself; I just wanted to update you on where I'm at.

**Comment by lbussy** [comment]
That happens - Windows is especially challenging with that.

You can try to manually delete the ./.pio/libdeps directory inside the project.  That's effectively the same thing.  The end result we are looking for is forcing the library dependencies to update.

In the case of that particular error, it's the fault of a forced dependency that is not even used in this project.  Let me try to clean that up.  I prefer letting the upstream authors manage their own code but sometimes they don't have the same focus.

**Comment by lbussy** [comment]
Updated [Keg Cop Alpha](https://web.brewflasher.com/fw/81/) to 1.1.0-Alpha.3

`git pull` on the `taplist_io` branch to get the current changes.  You'll probably want to do that clean command (or delete the `./.pio/libdeps` directory) to be sure.

**Comment by austinpe** [comment]
![image](https://user-images.githubusercontent.com/587046/176699923-6e052966-5fe4-4203-906d-54496ea703a0.png)

**Comment by lbussy** [comment]
Excellent! Try the current version in Brewflasher though, there have been a lot of platform changes which may help your stability issues.

**Comment by lbussy** [comment]
Watchdog Timer.  Means it locked up for whatever reason.

**Comment by austinpe** [comment]
It seemed good for as long as it was up (we just had a power surge).
I can't seem to download the uptime.csv anymore, though. The page loads, but right-click -> download doesn't result in anything.
I was checking the "about" page occasionally and I believe it was already at 16 hours or so before this power surge.

Anyways, the platform update seems to have resolved the crashing.
I'm flashing Alpha.4 right now and will keep you updated.
Feel free to mark this issue as resolved; I can always re-open if problems crop up again 😄

**Comment by lbussy** [comment]
Yeah unfortunately the new platform libraries broke the SPIFFS editor.  Now in theory I should not need it when I am done, but I use it a lot in development.  Not sure what's up with that.
