### ISSUE TITLE
Telemetry data visualization via Grafana [was: Question about MQTT topic structure and JSON packet schema]

### ISSUE THREAD

**Issue by amotl** [lbussy/keg-cop#29]
Dear Lee,

it is fun to see what you are working on over here. It looks like an excellent project. Kudos!

May I humbly ask you a specific question, as I see you are using MQTT within your architecture. In the README, it says:

> Keg Cop will report pours to Raspberry Pints via MQTT or a web endpoint with a generic JSON packet.

Can you outline the typical JSON message(s) emitted by this appliance, and the corresponding MQTT topic structure? Is it some measurement values?

I am asking because I am thinking that [Kotori] may be a sweet complement for your system [^1]. It is easy to write adapters for individual device families, and if that would fit together in any way, I will be happy to provide a corresponding adapter for Keg Cop.

With kind regards,
Andreas.

[Kotori]: https://github.com/daq-tools/kotori
[^1]: Edit: For effortless telemetry data recording and visualization via Grafana.

**Comment by amotl** [comment]
Hi again,

I see that I asked too quickly before dedicating some time to browse the API documentation [^1] and the documentation of the JSON models [^2]. Apologies.

[^3] and [^4] would be the payloads which describe the measurement values emitted by the system, right? I am now also seeing that the _Controller-Initiated Communication_ part of the API would probably be the right thing what I was looking for.

Specifically:
> The Target URL Report provides a holistic picture of the system to a custom/third-party endpoint. It is a timer-based POST; a change of state does not trigger it. As with all target system configurations within Keg Cop, it will post to HTTP only.
>
> -- https://docs.kegcop.com/en/latest/api/#url

I think this would be the right choice for integrating with Kotori, if that would make actual sense.

By chance, on the screenshots you provided on the _Operations and Configuration_ pages [^5], I haven't seen any about displaying graphs of measurement values over time. Maybe I am missing them. On the other hand, if such a feature is not implemented within Keg Cop yet, but you think it would be nice to have, then I will be happy to support.

With kind regards,
Andreas.

[^1]: https://docs.kegcop.com/en/latest/api/index.html
[^2]: https://github.com/lbussy/keg-cop/tree/main/jsonmodels
[^3]: https://github.com/lbussy/keg-cop/blob/main/jsonmodels/Temps%20JSON.md
[^4]: https://github.com/lbussy/keg-cop/blob/main/jsonmodels/Flow%20JSON.md
[^5]: https://docs.kegcop.com/en/latest/operations/

**Comment by lbussy** [comment]
The intention was always that this would be part of an extensible system of systems.  @thorrak has been "going to finish" [KegScreen](http://www.kegscreen.com/) for a while now.  Maybe if I get enough people to help me shame him, he will. 😉 

Anyway, so if such a picture over time were desired, the "upstream" should handle that.

My main target was to be the "physical" connection and own those measurements, where KEgScreen would build the fancy tap list.

**Comment by amotl** [comment]
All right. Maybe @thorrak is interested as well, otherwise I will not step on anyones toes. I am looking at eyecandy like the weather dashboards we are operating over at https://weather.hiveeyes.org/, for example [^1].

It is sweet to determine long-term trends and get a different grip on the telemetry data which is already emitted by the system. As mentioned above, I don't even know if that would be an actual benefit to your community at all. Probably it would be a better fit for a brewing rig?

[^1]: https://weather.hiveeyes.org/grafana/d/YVm0P1miz/meteogramm-messwerte-and-vorhersage

**Comment by lbussy** [comment]
You are absolutely not out of line, I'm all ears.  That's the best part of Open Source, everyone's ideas count.

I'll poke John to read this and see what he thinks.  It's possible there's complimentary work to what he wants to do.

**Comment by lbussy** [comment]
Hey @amotl, I am going to close this as not an issue - but if you are interested in this project and you'd like to see additional support in MQTT, for instance, let me know.  Right now, I think the webhook functionality could send JSON anywhere you like and be ingested as JSON.  I had another question about a complete (and standards-based) MQTT setup, so it's rolling around in my head for use.
