### ISSUE TITLE
Multiple names for "temperature control enabled" setting

### ISSUE THREAD

**Issue by thorrak** [lbussy/keg-cop#35]
The setting to enable/disable temperature control is called two different things in the code. It is called "controlenabled" when being output as part of the settings JSON, but the field to set it is called "enablecontrol"

Where it is output:
https://github.com/lbussy/keg-cop/blob/bde8c08835e458cf0ff198d6b74ee577ccd34d9d/src/webpagehandler.cpp#L396

Where it is read:
https://github.com/lbussy/keg-cop/blob/bde8c08835e458cf0ff198d6b74ee577ccd34d9d/src/webpagehandler.cpp#L761

**Comment by thorrak** [comment]
Another place it is referred to as "controlenabled": https://github.com/lbussy/keg-cop/blob/bde8c08835e458cf0ff198d6b74ee577ccd34d9d/src/jsonconfig.cpp#L447

**Comment by lbussy** [comment]
Fix in `devel`.
