### ISSUE TITLE
Multiple names for sensor enabled/sensor calibration settings

### ISSUE THREAD

**Issue by thorrak** [lbussy/keg-cop#36]
Similar to #35, the various temp sensor settings are called different things depending on if it's in the JSON being emitted or the form being posted back. Example for the room sensor:

Called "calroom" / "enableroom" when being posted back: https://github.com/lbussy/keg-cop/blob/bde8c08835e458cf0ff198d6b74ee577ccd34d9d/src/webpagehandler.cpp#L815

but just called "room" / "roomenabled" when being emitted in the JSON: https://github.com/lbussy/keg-cop/blob/bde8c08835e458cf0ff198d6b74ee577ccd34d9d/src/jsonconfig.cpp#L449

**Comment by lbussy** [comment]
Admit it - you hated seeing me close out all those other issues.

**Comment by thorrak** [comment]
When you get bored, you start new projects. Just looking out for the rest of us here!

**Comment by lbussy** [comment]
Fix in `devel`.
