### ISSUE TITLE
Errors and then only 404 pages after clicking on main page Temp Bar or Control point: Keg Sensor link

### ISSUE THREAD

**Issue by rkhanso** [lbussy/keg-cop#51]
I've posted some info at https://www.homebrewtalk.com/threads/keg-cop-keg-monitoring-and-control.692880/page-6#post-9300514 

When I click on the tan(ish) bar showing temperature on the main Keg Cop (ESP32) web page, I get two error messages:
Settings Error: Settings update failed.
Temps Warning: Unable to retrieve temperature data.

After that happens, when I use the menu to choose any other page, I get a 404 error. The only page that doesn't happen on is the external Keg Cop documentation menu link.  I can't get out of the 404 error loop using the menu at all. Only when I manually remove the /404 in the URL can I get back to the Keg Cop (ESP32) web gui.  This also happens when I'm on the Temperature Sensors for Kegerator page and click on the link "Control point: Keg Sensor"  -- the same exact results as previously explained.

If I never click on those two links, the Keg Cop web page (ESP32) works perfectly.

I get the same results in both Brave and Edge browsers.

**Comment by lbussy** [comment]
I don't have temperature sensors hooked up at the moment (insert long story/standard disclaimer about me moving), so I need to get that set up before I can do any testing.  I have if/then blocks in C++ and JS to take different paths if there are no temp sensors detected.

**Comment by rkhanso** [comment]
Your comment made me think about my configuration. I have space in the single-sided PCB for 3 temp sensors, but only have one connected at the moment. I checked my Keg Cop config and see that I had 2 other sensors enabled. Thinking this might be the cause of the error and the 404 loop, I disabled all but the one sensor actually connected at this moment....but it didn't make any difference. Still the same error messages as well as the 404 loop after clicking on those two links mentioned above.

**Comment by lbussy** [comment]
Yeah either way it should not `404` so I broke something.  :)

**Comment by lbussy** [comment]
Took care of the 404 loop under #60, which was a separate issue.  Looking at the reason the temps page is broken now.

**Comment by rkhanso** [comment]
Hello Lee,

I’ll give the Development release a try. I still notice that the 404 error loop is there in the main 1.1.0 version.

**Comment by lbussy** [comment]
Give me about an hour to push a new `devel` version.  I think I have it licked.

**Comment by lbussy** [comment]
Okay - `devel` should be good to test.

**Comment by rkhanso** [comment]
I also noticed a spelling error – Temperatire



 

From: Roger Hanson ***@***.***> 
Sent: Tuesday, July 26, 2022 12:32 PM
To: 'lbussy/keg-cop' ***@***.***>; 'lbussy/keg-cop' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [lbussy/keg-cop] Errors and then only 404 pages after clicking on main page Temp Bar or Control point: Keg Sensor link (Issue #51)

 

Thanks,

The 404 problem certainly appears to be fixed. But I do now get a different problem. It looks like a possible typo in the web page link.
When looking at the “Temperatures” page and clicking on one of the tan/orange temperatures shown, it goes to a bad link (see in the screenshot below)

 

192.168.2.247settings.htm’s DNS address could not be found. Diagnosing the problem.

DNS_PROBE_POSSIBLE

 

 

Another thing that I think is wrong in the new code, but I can’t be 100% positive since my wiring or homemade PCB may be suspect…..

I can’t calibrate the flow meter with the new devel firmware. I was able to successfully calibrate it in 1.0.0, however.


When I go to the calibrate page, Select Tap 9 (that’s the one and only I’m using since the 1-sided PCB made it easier), Config by volume, enter in some ounces measured, but don’t get a 0 to show up in the Pulses box until the flow starts. No pulses seen at all.

**Comment by rkhanso** [comment]
I just noticed an inconsistency in the Taps Settings/Configuration. 

In the dropdown for Taps, it shows 1-9

When you choose a tap, it shows in the GUI the correct tap number for all except for Tap 9 (It says Tap 8 Configuration)

 



From: Roger Hanson ***@***.***> 
Sent: Tuesday, July 26, 2022 3:36 PM
To: 'lbussy/keg-cop' ***@***.***>; 'lbussy/keg-cop' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [lbussy/keg-cop] Errors and then only 404 pages after clicking on main page Temp Bar or Control point: Keg Sensor link (Issue #51)

 

I also noticed a spelling error – Temperatire



 

From: Roger Hanson ***@***.*** ***@***.***> > 
Sent: Tuesday, July 26, 2022 12:32 PM
To: 'lbussy/keg-cop' ***@***.*** ***@***.***> >; 'lbussy/keg-cop' ***@***.*** ***@***.***> >
Cc: 'Author' ***@***.*** ***@***.***> >
Subject: RE: [lbussy/keg-cop] Errors and then only 404 pages after clicking on main page Temp Bar or Control point: Keg Sensor link (Issue #51)

 

Thanks,

The 404 problem certainly appears to be fixed. But I do now get a different problem. It looks like a possible typo in the web page link.
When looking at the “Temperatures” page and clicking on one of the tan/orange temperatures shown, it goes to a bad link (see in the screenshot below)

 

192.168.2.247settings.htm’s DNS address could not be found. Diagnosing the problem.

DNS_PROBE_POSSIBLE

 

 

Another thing that I think is wrong in the new code, but I can’t be 100% positive since my wiring or homemade PCB may be suspect…..

I can’t calibrate the flow meter with the new devel firmware. I was able to successfully calibrate it in 1.0.0, however.


When I go to the calibrate page, Select Tap 9 (that’s the one and only I’m using since the 1-sided PCB made it easier), Config by volume, enter in some ounces measured, but don’t get a 0 to show up in the Pulses box until the flow starts. No pulses seen at all.

**Comment by lbussy** [comment]
> When you choose a tap, it shows in the GUI the correct tap number for all except for Tap 9 (It says Tap 8 Configuration)

Man if that's all you've found I did pretty good!  :)

Got it, fixed in my local version and will be in the release.

**Comment by lbussy** [comment]
Okay - your email responses are getting messy and I am missing things.  Can you trim the old responses when you reply?

> I also noticed a spelling error – Temperatire

Added #68 

> When you choose a tap, it shows in the GUI the correct tap number for all except for Tap 9 (It says Tap 8 Configuration)

Added #69

> When looking at the “Temperatures” page and clicking on one of the tan/orange temperatures shown, it goes to a bad link (see in the screenshot below)

No images come through when you reply via email.  You either need to click on the "View in GitHub" or describe more thoroughly.  Right now I am unable to reproduce this one.

> I can’t calibrate the flow meter with the new devel firmware. I was able to successfully calibrate it in 1.0.0, however.
>
>When I go to the calibrate page, Select Tap 9 (that’s the one and only I’m using since the 1-sided PCB made it easier), Config by volume, enter in some ounces measured, but don’t get a 0 to show up in the Pulses box until the flow starts. No pulses seen at all.

Not following here either.  You should not enter ounces until after you have dispensed the volume, then enter ounces, then it should calibrate.  Is that not working like that?

**Comment by rkhanso** [comment]
Regarding calibrating trouble:

 

When calibrating the flow meter I choose the correct tap (#9) and then check the Volume button and press “Do Config by Volume". 

In the older versions of firmware, on the next screen a 0 would populate right away in the Pulses box and when I got some flow going, the count would increase.

In the Development firmware, a zero doesn’t immediately show up in the Pulses box and nothing happens when get some flow going. Pulses don’t increment, but the fact that it behaves different between v1.0.0 and devel makes me think it’s a firmware/coding problem and nothing on my end. It doesn’t matter whether I enter any ounces first or not, it doesn’t appear to count pulses. I’ve tried choosing different Tap numbers and that doesn’t make any difference either (didn’t expect it to though).

 

If I go back to V 1.0.0, I can calibrate with no trouble.

 

I put a screenshot on the homebrewtalk thread.

**Comment by lbussy** [comment]
> When calibrating the flow meter I choose the correct tap (#9) and then check the Volume button and press “Do Config by Volume". In the older versions of firmware, on the next screen a 0 would populate right away in the Pulses box and when I got some flow going, the count would increase. In the Development firmware, a zero doesn’t immediately show up in the Pulses box and nothing happens when get some flow going. Pulses don’t increment, but the fact that it behaves different between v1.0.0 and devel makes me think it’s a firmware/coding problem and nothing on my end. It doesn’t matter whether I enter any ounces first or not, it doesn’t appear to count pulses. I’ve tried choosing different Tap numbers and that doesn’t make any difference either (didn’t expect it to though).

I've opened #70 for this. 

Be sure to follow the new issues for these, as this one was for the 404 and is closed.

**Comment by lbussy** [comment]
Updated [Keg Cop Beta](https://web.brewflasher.com/fw/90/) to 1.1.1-Beta.2

**Comment by rkhanso** [comment]
Thanks,

The 404 problem certainly appears to be fixed. But I do now get a different problem. It looks like a possible typo in the web page link.
When looking at the “Temperatures” page and clicking on one of the tan/orange temperatures shown, it goes to a bad link (see in the screenshot below)

 

192.168.2.247settings.htm’s DNS address could not be found. Diagnosing the problem.

DNS_PROBE_POSSIBLE

 

 

Another thing that I think is wrong in the new code, but I can’t be 100% positive since my wiring or homemade PCB may be suspect…..

I can’t calibrate the flow meter with the new devel firmware. I was able to successfully calibrate it in 1.0.0, however.


When I go to the calibrate page, Select Tap 9 (that’s the one and only I’m using since the 1-sided PCB made it easier), Config by volume, enter in some ounces measured, but don’t get a 0 to show up in the Pulses box until the flow starts. No pulses seen at all.

**Comment by lbussy** [comment]
Moved these to #149 and #150.
