### ISSUE TITLE
Incorrect copyright date

### ISSUE THREAD

**Issue by thorrak** [lbussy/keg-cop#6]
https://github.com/lbussy/keg-cop/blob/401cf2c7e76c4b54fadf538f9cc6c7594caab9e6/data/index.htm#L109

excuse me while I go cry about the implication.

**Comment by lbussy** [comment]
I need to figure out how to dynamically set those repetitive strings.

**Comment by thorrak** [comment]
Let me know if you figure it out. Seems like it would require either setting a "common string JSON endpoint" or parsing the HTML on its way out of the device. :(

**Comment by lbussy** [comment]
There is a way to do some string replacement in the asynch web server.  I'm just not sure what fresh hell it would dredge up.

**Comment by lbussy** [comment]
Pushed to `devel`, closing.
