### ISSUE TITLE
Settings Error: Settings update failed.

### ISSUE THREAD

**Issue by ceesnz** [lbussy/keg-cop#64]
Version 1.0.0 works fine
Just installed version 1.1.0. Reconnected to my wifi.  that works. Web page works. However, none of the settings changes can be saved. Getting error Settings Error: Settings update failed.
Not sure where and how to debug

**Comment by lbussy** [comment]
Yep, working on this.  Need a couple more hours of peace to knock it out.  Hopefully tomorrow.

**Comment by ceesnz** [comment]
Thanks,
Just stumbled across your project today.  Looks awesome.
I went down the Kegbot/kegboard rabbit hole first and that project, even though impressive, is far too complicated.
Yours looks great. Can’t wait to see what KegScreen integration is going to look like.

Don’t have your pcb’s yet but will very likely get them.
I found the pins you use so manage to test without pcb

If your not to busy can you tell me if your project updates to a mqtt server and how often.  I might be able to integrate this into my Home Assistant project

Cheers for New Zealand

Cees

**Comment by lbussy** [comment]
> Can’t wait to see what KegScreen integration is going to look like.

Me too.  I keep bugging @thorrak about it. :)

> If your not to busy can you tell me if your project updates to a mqtt server and how often.  I might be able to integrate this into my Home Assistant project

Right now MQTT is rather (okay, VERY) basic.  I put it in so that people who are emotionally invested in Raspberry Pints could use these controllers.  You can check the [API](https://docs.kegcop.com/en/latest/api/index.html) page and see the [RPints MQTT format](https://docs.kegcop.com/en/latest/api/index.html#raspberry-pints).  It's not "real" MQTT, but it does report each pour.

I'm not against adding more complete reporting via MQTT, I've just not had anyone want to use it yet.

**Comment by lbussy** [comment]
Updated [Keg Cop Beta](https://web.brewflasher.com/fw/90/) to 1.1.1-Beta.1

**Comment by lbussy** [comment]
I just pushed changes to `devel` in which this is fixed.

**Comment by austinpe** [comment]
It might be my esp32, but with 1.1.1-Beta.1 an AP doesn't initiate upon successful FLASH. 
Further, trying the double reset and grounding pin 13 didn't raise the AP either.

I didn't have a lot of time; I'll try tomorrow with another esp32.

**Comment by lbussy** [comment]
> It might be my esp32, but with 1.1.1-Beta.1 an AP doesn't initiate upon successful FLASH.

I'd recommend watching the serial monitor and seeing what's going on there.  That may be the most highly tested area of the whole thing. :)

If I reset, wait about half a second and then reset again (the feature times out after 3 seconds), I get this:

```
1970-01-01T00:00:00Z N: Serial logging started at 115200.
1970-01-01T00:00:00Z N: DRD: Portal requested.
1970-01-01T00:00:02Z N: Entered portal mode; name: kegcop, IP: 192.168.4.1.
```

**Comment by austinpe** [comment]
😄 it was my USB cable. Not enough voltage caused brown out trigger.
My mistake!

**Comment by lbussy** [comment]
Updated [Keg Cop Beta](https://web.brewflasher.com/fw/90/) to 1.1.1-Beta.2
