### ISSUE TITLE
Internal & External Tap IDs don't match

### ISSUE THREAD

**Issue by thorrak** [lbussy/keg-cop#7]
The internal tap IDs (0-8) and the tap IDs as displayed in the interface (1-9) don't match

<img width="739" alt="Screen Shot 2021-07-08 at 10 00 39 AM" src="https://user-images.githubusercontent.com/2457900/124935453-ae484f00-dfd3-11eb-980e-8d5ce234db85.png">

**Comment by thorrak** [comment]
The issue with this is that KegScreen tracks/presents the internal tap ID to users which will be off by one vs. the IDs the user would see in the Keg Cop interface. 

My preference would be to switch to use the "external" tap ID everywhere (internally) in Keg Cop - but if you want to tag this as "wontfix" I can hardcode the off-by-one shift in the relevant KegScreen screens/functions.

**Comment by lbussy** [comment]
What ever happened to separating business and data functions?  😀

**Comment by lbussy** [comment]
Not against this but I'm not sure where it will end.  Is it only the hashes that mess you up?  Or is it that `/api/v1/config/taps/` is zero-based?  I'd prefer to leave the "data" in close correlation to the actual internal (zero-based" arrays, but if there are display portions that are causing confusion we can talk about how best to handle that.

My thinking was if someone used KegScreen, they could name them whatever they want.  I could add a "tap name" field I guess to be pushed by KegScreen?

**Comment by thorrak** [comment]
As an example -

I currently don’t cache/support updating PPU inside the KegScreen interface. When the user wants to calibrate the sensor/update PPU I link them to the Keg Cop interface’s calibration workflow. Inside KegScreen, the user would see that they are viewing/updating “Keezer - Tap 0” but in the Keg Cop interface they would need to select to calibrate “Tap 1”.

My thought is that the most straightforward/long-lasting fix would be to swap the zero-based index everywhere inside Keg Cop for the one-based index being displayed, but I can also alternatively change the function that generates the tap name to just add 1 to the tap number inside KegScreen.

**Comment by lbussy** [comment]
Changing an index in C++ to be 1-based would be a headache waiting to happen.  What do you think about adding a "name" field to the data for the meter?

**Comment by lbussy** [comment]
@thorrak did you have an opinion here?

**Comment by thorrak** [comment]
I don't have an opinion, other than to lock down _something_. I think I finished the missing pieces of your "external tap ID label" support in #12 , but didn't go through and test it. If that's the route you want to take with this, I'm fine consuming that and having the user refer to that when linking Keg Cop taps to KegScreen taps.

**Comment by lbussy** [comment]
Well, let's assume we did till someone tells us it's broken :)

**Comment by thorrak** [comment]
> Well, let's assume we did till someone tells us it's broken :)

I MEAN. The someone here is me, soooo....

**Comment by lbussy** [comment]
I guess we do need a way to assign them.  They should probably default to `index + 1` and allow them to be set to custom numbers.

**Comment by lbussy** [comment]
Does the solution I suggested in #18 solve this too?

**Comment by thorrak** [comment]
> Does the solution I suggested in #18 solve this too?

I don't think so. I thought where we landed was that there needed to be some kind of configurable key that existed internal to Keg Cop that would be provided in each of the reports and could be used to link those reports to KegScreen tap IDs. Controller ID + Keg Cop tap ID is fine, but I need a way to either definitively derive the Keg Cop _internal_ tap ID (and controller ID) for providing data back to Keg Cop from KegScreen or have some kind of key that KegScreen can provide that will let Keg Cop do the derivation.

**Comment by lbussy** [comment]
I'm calling this fixed with `taps[n].label`.  You good with that?

``` json
{
  "imperial": true,
  "taps": [
    {
      "tapid": 0,
      "label": 1,
      "pin": 4,
      "ppu": 21120,
      "name": "Pudswiller Doors",
      "capacity": 5,
      "remaining": 4.2,
      "taplistioTap": 0,
      "active": true,
      "calibrating": false
    }
```
