### ISSUE TITLE
Temp sensor calibration doesn't seem to work in v1.1.1-Beta.1 [devel] (817678a)

### ISSUE THREAD

**Issue by rkhanso** [lbussy/keg-cop#71]
Similar to a previous and now closed issue #9, when I change the numbers on the Temperature Sensor Control page, nothing changes in the temperature output on the Temperature Sensors data page. Calibration is not possible.

**Comment by lbussy** [comment]
This is fixed in `devel` (not available in BrewFlasher Beta yet.)

**Comment by lbussy** [comment]
Updated [Keg Cop Beta](https://web.brewflasher.com/fw/90/) to 1.1.1-Beta.2
