### ISSUE TITLE
Malformed links when using IP instead of mDNS

### ISSUE THREAD

**Issue by rkhanso** [lbussy/keg-cop#72]
When on the Temperatures page and clicking on any of the tan/orange temperature graph/columns, the link it wants to take you doesn't exist.  It appears to want to take you to the Settings page, but the URL has a typo.

http://192.168.2.247settings.htm/#sensorcontrol   <<<---where it wants to take me, but a bad link.
http://192.168.2.247/settings/#sensorcontrol  <<<--- I think this is where you intended it should take me.

**Comment by lbussy** [comment]
"You people" that don't use mDNS ... :)

Do you have the ability to test by name?  More at:

https://docs.kegcop.com/en/latest/troubleshooting/index.html

**Comment by rkhanso** [comment]
I installed the Bonjour Browser and only get spinning circle. Nothing ever populates in the "Available Bonjour Services" window.

I checked my Windows security settings. I have the LAN firewall (Domain Network and Private Network) turned off.  If there are other security settings that might need to be adjusted, I'm not sure what they'd be. I also have an Untangle Firewall, but since this should be scanning Local traffic, I'm not sure that would actually come into play (though I do have 3 VLANs). Everything else on the LAN works OK. No trouble.

**Comment by rkhanso** [comment]
I'm sorry to have brought this issue up now. I did get MDNS sort of working and am able to access the ESP32 via //kegcop/ now and the web pages work correctly. 

But I'm sure I won't be the last person using the IP address instead of hostname in the URL.

**Comment by lbussy** [comment]
Ah just teasing you.  I need to get it fixed because there are some folks who for whatever reason cannot use mDNS.

**Comment by lbussy** [comment]
This is fixed in `devel`.

**Comment by rkhanso** [comment]
Is the devel you mention below different than the version that Brewflasher will use? I ask, because I used Brewflasher to get the devel firmware and it’s still looking like a bad link when using the IP address for URL.

 

Or might I need to wait until a new devel version is uploaded to Brewflasher or download the newest update somewhere else?

 

I need to go back to version 1.0.0 anyway, because that’s the only version that the flow meter works for me.

**Comment by lbussy** [comment]
> Is the devel you mention below different than the version that Brewflasher will use? 

Yes.  When I get one or two more things fixed I'll post another to BrewFlasher.

**Comment by lbussy** [comment]
Updated [Keg Cop Beta](https://web.brewflasher.com/fw/90/) to 1.1.1-Beta.2
