### ISSUE TITLE
Feature request - convert the Solenoid pin to a Temperature Controlled option for a Tower Fan

### ISSUE THREAD

**Issue by rkhanso** [lbussy/keg-cop#86]
I have a tower temp probe and a fan to blow cold air up there when needed. The fan is pretty noisy and I don't want it running all the time. 
I currently use CraftbeerPi3 to control my Kegerator and it has the ability to turn the fan on/off based on the tower temperature probe. Could you add this feature into KegCop so that it can do the same?

**Comment by lbussy** [comment]
This should be possible to do by swapping the solenoid pin over to be used by a thermostat control.  Putting it in the "enhancements" list.

**Comment by lbussy** [comment]
Something like this?

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/9092188/183517700-e89cf354-8cb2-4cb4-bcec-0df369d9a250.png">

**Comment by rkhanso** [comment]
Perfect!

**Comment by lbussy** [comment]
Right, I think I have like a 10 second min time to keep it from hammering the relay should something go wrong.

I need to test it and all that, but the bones should be there anyway.

**Comment by lbussy** [comment]
If you want to test this, BrewFlasher has been updated to [Keg Cop Alpha](https://web.brewflasher.com/fw/90/) to 1.2.0-Alpha.1.

This should be the release I made earlier tonight (1.1.1) with all the bug fixes plus the Tower Fan.

I am headed out for a week and a half, so if you have issues just note them here and I'll get them when I get back.

**Comment by lbussy** [comment]
Okay this is in `feature1.2` now.  @thorrak will be adding a "try this" for you here in a few (to see if your SPIFFS memory is bad) and you can test this code.  Under -> Settings -> Temperature -> Control, you can enable the Tower Fan control and setpoint.  When this is enabled, the "Solenoid" control will be disabled as this repurposes that pin.

Here's the control section:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/9092188/186461393-5d98da74-11ee-4d9c-9d10-ced2b9c0cad5.png">

This is how the icon looks when not on:

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/9092188/186461468-be28c335-8716-4e57-ae87-bb42336ad0b5.png">

This is how it looks when it is on/blowing:

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/9092188/186461706-1c1b9fc2-5ff9-45fa-90e7-5f9bd9aa488a.png">

I'm closing this now as "complete."  It will be in 1.2 when I release it.
