### ISSUE TITLE
Default WiFi AP password in code doesn't match default in JSON

### ISSUE THREAD

**Issue by thorrak** [lbussy/keg-cop#95]
The default WiFi AP password in the config JSON is "kegcop21":

https://github.com/lbussy/keg-cop/blob/916eadae8d747e886462713aa27ba03e86c06eda/data/config.json#L4

This differs from the fallback if no config file is present:

https://github.com/lbussy/keg-cop/blob/916eadae8d747e886462713aa27ba03e86c06eda/src/config.h#L271

**Comment by lbussy** [comment]
"You did it wrong"

**Comment by thorrak** [comment]
Yes, that is in fact how I discovered this

**Comment by lbussy** [comment]
Merged to `devel`.
